[package]
name = "saffron-sid"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Saffron Ingredient Database client library"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
