[package]
name = "saffron-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Code generator for the Saffron programming language"

[dependencies]
saffron-ast = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
