[package]
name = "saffron-typeck"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Type checker for the Saffron programming language"

[dependencies]
saffron-ast = { workspace = true }
saffron-sid = { workspace = true }
thiserror = { workspace = true }
